CREATE SCHEMA CURRENCY_SCHEMA;

CREATE TABLE CURRENCY_SCHEMA.CURRENCY
(
    ID   BIGINT,
    NAME VARCHAR(200) NOT NULL,

    CONSTRAINT PK_CURRENCY PRIMARY KEY (ID)
);


CREATE TABLE CURRENCY_SCHEMA.EXCHANGE_RATE
(
    ID          BIGINT,
    "DATE"      DATE    NOT NULL,
    RATE        NUMERIC NOT NULL,
    CURRENCY_ID BIGINT  NOT NULL,

    CONSTRAINT PK_EXCHANGE_RATE PRIMARY KEY (ID),
    CONSTRAINT FK_EXCHANGE_RATE_CURRENCY_ID FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY_SCHEMA.CURRENCY (ID)
);
